#!/bin/bash

# Kill POS if we're doing stupid shit.
HOG_COUNTER=0
while true; do
    HOG=$(top -b -n 1 | grep pos2 | awk '$9 > 90 {print $1}')
    if [ ! -z "$HOG" ]; then
        counter_time=$(date)
        HOG_COUNTER=$(expr ${HOG_COUNTER} + 1)
        echo "$counter_time - Found a hog: $HOG - ${HOG_COUNTER} counters." >> /kbk/log/high_mem_kill_log
    else
        HOG_COUNTER=0
    fi
    if [ $HOG_COUNTER -gt 2 ]; then
        kill_time=$(date)
        echo "$kill_time - Found a hog: $HOG.  $HOG_COUNTER counters.  Killing $HOG." >> /kbk/log/high_mem_kill_log
        kill $HOG
    fi
    sleep 30s
done