apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\bubth\go\bin\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kbk
  name: kbk
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: kbk
status:
  loadBalancer: {}
