apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kbk-cluster-resources
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/bubthegreat/kbk.git
    targetRevision: HEAD
    path: k8s/cluster-resources
  
  destination:
    server: https://kubernetes.default.svc
    # No namespace - these are cluster-wide resources
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

