apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kbk-staging

resources:
  - namespace.yaml
  - kbk-httproute.yaml
  - ../../base

# Add namespace to all resources
commonLabels:
  environment: staging

commonAnnotations:
  deployed-branch: claude/prod-staging-db-issues-dnrzm6
  deployed-sha: 8b01c81

patchesStrategicMerge:
  - kbk-configmap.yaml

images:
  - name: bubthegreat/kbk
    newTag: claude-prod-staging-db-issues-dnrzm6-8b01c81

