/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/bubthegreat/kbk/golib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */






/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// DirectionLookup converts a direction string to a numeric direction value.
// Returns -1 if the direction is not recognized.
// Matches the C function: int direction_lookup(char *dir)
//

extern int DirectionLookup(char* p0);

// PositionLookup finds a position by name with case-insensitive prefix matching.
// Returns -1 if not found.
// Matches the C function: int position_lookup(const char *name)
//

extern int PositionLookup(char* p0);

// SexLookup finds a sex value by name with case-insensitive prefix matching.
// Returns -1 if not found.
// Matches the C function: int sex_lookup(const char *name)
//

extern int SexLookup(char* p0);

// SizeLookup finds a size value by name with case-insensitive prefix matching.
// Returns -1 if not found.
// Matches the C function: int size_lookup(const char *name)
//

extern int SizeLookup(char* p0);

// NumberRange generates a random number between from and to (inclusive).
// Matches the C function: int number_range(int from, int to)
//

extern int NumberRange(int p0, int p1);

// NumberPercent generates a percentile roll (1-100).
// Matches the C function: int number_percent(void)
//

extern int NumberPercent();

// NumberDoor generates a random door direction (0-5).
// Matches the C function: int number_door(void)
//

extern int NumberDoor();

// NumberBits generates a random number with the specified number of bits.
// Matches the C function: int number_bits(int width)
//

extern int NumberBits(int p0);

// Dice rolls dice with the specified number and size (e.g., 3d6).
// Matches the C function: int dice(int number, int size)
//

extern int Dice(int p0, int p1);

// NumberFuzzy adds a small random variation to a number.
// The number can be decreased by 1, stay the same, or increased by 1.
// Matches the C function: int number_fuzzy(int number)
//

extern int NumberFuzzy(int p0);

// Interpolate performs simple linear interpolation.
// Matches the C function: int interpolate(int level, int value_00, int value_32)
//

extern int Interpolate(int p0, int p1, int p2);

// UMin returns the minimum of two integers.
// Matches the C macro: UMIN(a, b)
//

extern int UMin(int p0, int p1);

// UMax returns the maximum of two integers.
// Matches the C macro: UMAX(a, b)
//

extern int UMax(int p0, int p1);

// URange clamps a value between a minimum and maximum.
// Matches the C macro: URANGE(a, b, c)
//

extern int URange(int p0, int p1, int p2);

// StrCmp performs case-insensitive string comparison.
// Returns 1 (true) if strings are different, 0 (false) if they are the same.
// This matches the C convention where str_cmp returns TRUE if different.
// Matches the C function: bool str_cmp(const char *astr, const char *bstr)
//

extern int StrCmp(char* p0, char* p1);

// StrPrefix checks if astr is a case-insensitive prefix of bstr.
// Returns 1 (true) if astr is NOT a prefix of bstr, 0 (false) if it is.
// This matches the C convention.
// Matches the C function: bool str_prefix(const char *astr, const char *bstr)
//

extern int StrPrefix(char* p0, char* p1);

// StrSuffix checks if astr is a case-insensitive suffix of bstr.
// Returns 1 (true) if astr is NOT a suffix of bstr, 0 (false) if it is.
// This matches the C convention.
// Matches the C function: bool str_suffix(const char *astr, const char *bstr)
//

extern int StrSuffix(char* p0, char* p1);

// StrInfix checks if astr appears anywhere in bstr (case-insensitive).
// Returns 1 (true) if astr is NOT found in bstr, 0 (false) if it is found.
// This matches the C convention.
// Matches the C function: bool str_infix(const char *astr, const char *bstr)
//

extern int StrInfix(char* p0, char* p1);

// Capitalize returns a string with the first letter capitalized and the rest lowercase.
// Note: This returns a pointer to a static buffer, matching C behavior.
// The caller should not free this pointer.
// Matches the C function: char *capitalize(const char *str)
//

extern char* Capitalize(char* p0);

// SmashTilde replaces all tilde characters (~) with dashes (-).
// This modifies the string in place.
// Matches the C function: void smash_tilde(char *str)
//

extern void SmashTilde(char* p0);

#ifdef __cplusplus
}
#endif
